language: node_js
node_js:
  - "5"
  - "4"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
deploy:
  provider: script
  script: 'cd docs && npm run deploy'
  on:
    branch: master
